INSERT INTO asset (
    id,
    input_date,
    code_item,
    item_name,
    category,
    date_of_purchase,
    price,
    adjustment_date,
    location_item,
    condition_item,
    photo,
    amount
  )
VALUES (
    id :int INSERT INTO asset (
        id,
        input_date,
        code_item,
        item_name,
        category,
        date_of_purchase,
        price,
        adjustment_date,
        location_item,
        condition_item,
        photo,
        amount
      )
    VALUES (
        id:int,
        'input_date:date',
        'code_item:varchar',
        'item_name:varchar',
        'category:varchar',
        'date_of_purchase:date',
        'price:decimal',
        'adjustment_date:date',
        'location_item:varchar',
        'condition_item:varchar',
        'photo:varchar',
        amount:int
      );,
    'input_date:date',
    'code_item:varchar',
    'item_name:varchar',
    'category:varchar',
    'date_of_purchase:date',
    'price:decimal',
    'adjustment_date:date',
    'location_item:varchar',
    'condition_item:varchar',
    'photo:varchar',
    amount:int
  );